CREATE OR REPLACE TRIGGER ONBOARDING_R2
AFTER INSERT ON WEB_DOCS_OCR_DATA FOR EACH ROW 

DECLARE DECLARE V_NUM_ID VARCHAR2(15 CHAR);

BEGIN
    DELETE FROM ONBOARDING_LOGS;
    SELECT num_id INTO V_NUM_ID FROM DUAL LEFT JOIN BFP_PERSONA ON num_id = :NEW.COD_CLIENTE;
    IF V_NUM_ID IS NOT NULL THEN
        INSERT INTO ONBOARDING_LOGS (ID, LOGD) VALUES ( SECUENCE_ALL.NEXTVAL, CONCAT( 'NUMERO EXISTE EN TABLA ', V_NUM_ID));
    END IF;
END;