CREATE OR REPLACE TRIGGER ONBOARDING_R2_VALID_EMAIL
AFTER INSERT OR UPDATE ON WEB.WEB_DOCS_OCR_DATA FOR EACH ROW 
DECLARE 
    V_NUM_ID VARCHAR2(15 CHAR);
    V_ESTADO_AFILIADO VARCHAR2(3 CHAR);
    V_CORREO_ELECTRONICO VARCHAR2(100 CHAR);
    V_CORREO_ELECTRONICO2 VARCHAR2(100 CHAR);
    V_ESTADO_EMAIL1 VARCHAR2(1 CHAR);
    V_ESTADO_EMAIL2 VARCHAR2(1 CHAR);
BEGIN
    SELECT num_id INTO V_NUM_ID FROM DUAL LEFT JOIN RE.BFP_PERSONA ON num_id = :NEW.COD_CLIENTE;
    IF V_NUM_ID IS NOT NULL THEN
        SELECT  ESTADO_AFILIADO INTO V_ESTADO_AFILIADO  FROM  DUAL LEFT JOIN  RE.BFP_PERSONA ON num_id = :NEW.COD_CLIENTE; 
        IF V_ESTADO_AFILIADO = 'ACT' THEN          
            SELECT CORREO_ELECTRONICO INTO V_CORREO_ELECTRONICO FROM DUAL LEFT JOIN  RE.BFP_PERSONA ON num_id = :NEW.COD_CLIENTE;
            SELECT CORREO_ELECTRONICO2 INTO V_CORREO_ELECTRONICO2 FROM DUAL LEFT JOIN  RE.BFP_PERSONA ON num_id = :NEW.COD_CLIENTE;
            SELECT ESTADO_EMAIL1 INTO V_ESTADO_EMAIL1 FROM DUAL LEFT JOIN  RE.BFP_PERSONA ON num_id = :NEW.COD_CLIENTE;
            SELECT ESTADO_EMAIL2 INTO V_ESTADO_EMAIL2 FROM DUAL LEFT JOIN  RE.BFP_PERSONA ON num_id = :NEW.COD_CLIENTE;  
            IF  V_CORREO_ELECTRONICO IS NULL OR :NEW.CORREO_ELECTRONICO != V_CORREO_ELECTRONICO THEN
                IF V_CORREO_ELECTRONICO2 IS NULL OR :NEW.CORREO_ELECTRONICO != V_CORREO_ELECTRONICO2 THEN                  
                    IF V_ESTADO_EMAIL1 IS NOT NULL AND V_ESTADO_EMAIL1 = 'A'  OR  V_ESTADO_EMAIL2 IS NOT NULL AND V_ESTADO_EMAIL2 = 'A'THEN       
                        UPDATE RE.BFP_PERSONA SET CORREO_ELECTRONICO = :NEW.CORREO_ELECTRONICO WHERE  num_id = :NEW.COD_CLIENTE; 
                        COMMIT;                     
                    END IF;
                END IF;
            END IF;
        END IF;
    END IF;
END;