CREATE OR REPLACE  TRIGGER ONBOARDING_R2_VALID_INFO_ELECT4
AFTER INSERT OR UPDATE ON WEB_DOCS_OCR_DATA FOR EACH ROW 
DECLARE 
    V_NUM_ID VARCHAR2(15 CHAR);
    V_ESTADO_AFILIADO VARCHAR2(3 CHAR);
    V_ETAPA_INFO_ELECT NUMBER(2, 0);
BEGIN
    SELECT num_id INTO V_NUM_ID FROM DUAL LEFT JOIN BFP_PERSONA ON num_id = :NEW.COD_CLIENTE;
    IF V_NUM_ID IS NOT NULL THEN
        SELECT  ESTADO_AFILIADO INTO V_ESTADO_AFILIADO  FROM  DUAL LEFT JOIN  BFP_PERSONA ON num_id = :NEW.COD_CLIENTE; 
        IF V_ESTADO_AFILIADO = 'ACT' THEN          

            SELECT ETAPA_INFO_ELECT INTO V_ETAPA_INFO_ELECT FROM DUAL LEFT JOIN  BFP_PERSONA ON num_id = :NEW.COD_CLIENTE;       
            
            IF  V_ETAPA_INFO_ELECT IS NOT NULL AND V_ETAPA_INFO_ELECT != 4 THEN    
                UPDATE BFP_PERSONA SET ETAPA_INFO_ELECT = 4  WHERE  num_id = :NEW.COD_CLIENTE;                        
            END IF;           

        END IF;
    END IF;
END;