CREATE OR REPLACE TRIGGER "CPSAD"."CS_ACTUALIZA_ONBOARDING_R2" 
BEFORE UPDATE	
ON CPSAD.CS_ACTUALIZA_DATOS REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE 

BEGIN
   IF :NEW.ESTADO = 3 THEN
           update WEB.WEB_DOCS_OCR_DATA set ESTADO = 'C' where COD_CLIENTE = :new.nup;
    END IF;
END;